services:

  backend:
    build: ./backend
    container_name: loan-prediction-backend
    ports:
      - "8000:8000"
    networks:
      - fe-be
    restart: always

  frontend:
    build: ./frontend
    container_name: loan-prediction-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - fe-be
    restart: always


networks:
  fe-be: